version: '3'

services:
    app:
        build:
            context: .
        links:
            - mysql
        volumes:
            - ./:/var/www/recruitment

    nginx:
        image: nginx:1.13
        ports:
            - "8080:80"
        depends_on:
            - app
        volumes:
            - ./:/var/www/recruitment
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/

    mysql:
        image: mysql:5.7
        ports:
            - "33061:3306"
        volumes:
            - ./tests/data:/tests/data
        environment:
            - "MYSQL_DATABASE=test"
            - "MYSQL_USER=testuser"
            - "MYSQL_PASSWORD=password"
            - "MYSQL_ROOT_PASSWORD=verysecret"
