{% extends "layout.phtml" %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>Bookings</h2>
        </div>
    </div>


    <div class="row">
        <div class="col">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Reference</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Booking Date</th>
                </tr>
                </thead>
                <tbody>
                {% for booking in bookings %}
                <tr>
                    <td>{{ booking.getReference() }}</td>
                    <td>{{ booking.getCustomer().getFullName() }}</td>
                    <td>{{ booking.getBookingDate().format('D dS M Y') }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}