{% extends "layout.phtml" %}

{% block content %}
    <div class="row">
        <div class="col">
            <h2>Customers</h2>
        </div>
    </div>


    <div class="row">
        <div class="col">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">First Name</th>
                    <th scope="col">Surname</th>
                    <th scope="col">Address</th>
                    <th scope="col">Twitter Alias</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in allCustomers %}
                <tr>
                    <td>{{ customer.getFirstName() }}</td>
                    <td>{{ customer.getSurname() }}</td>
                    <td>{{ customer.getAddress() }}</td>
                    <td>{{ customer.getTwitterAlias() }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h2>Ordered by surname (descending)</h2>
            <p>
                {% for customer in customersSortedBySurname %}
                    {{ customer.getFullName() }}<br>
                {% endfor %}
            </p>
        </div>
    </div>

{% endblock %}